filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/SpringBootExample/info.log
  fields:
    service: api_info

- type: log
  enabled: true
  paths:
    - /var/log/SpringBootExample/error.log
  multiline.pattern: ^\[
  multiline.negate: true
  multiline.match: after
  fields:
    service: api_error

output.logstash:
  hosts: ["127.0.0.1:5044"]
