apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: pvc-pod
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: pvc-example