global:
  scrape_interval: 4s
  external_labels:
    monitor: "shark-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['192.168.13.82:19090']
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ['192.168.13.82:19113']