apiVersion: v1
kind: Service
metadata:
  name: springboot-example
spec:
  selector:
    app: springboot-example
  type: NodePort
  ports:
    - port: 7080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-example
spec:
  selector:
    matchLabels:
      app: springboot-example
  template:
    metadata:
      labels:
        app: springboot-example
    spec:
      containers:
        - image: shark0/springboot_example:69769be
          imagePullPolicy: IfNotPresent
          name: springboot-example