apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll-deploy
  labels:
    app: roll-example
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
   matchLabels:
     app: roll-example
  template:
    metadata:
      labels:
        app: roll-example
    spec:
      containers:
        - name: roll-example
          image: nginx:1.19.3 #1.14.2 #1.19.3
          ports:
            - containerPort: 80